name: bot_game

services:
  pg:
    image: postgres:16
    container_name: bot_game_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bot_game_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bot_game_test"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - bot_game_pgdata:/var/lib/postgresql/data

volumes:
  bot_game_pgdata: